version: '3.8'

services:
  web:
    container_name: kmd-web-3
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - default
      - kmd_default

networks:
  kmd_default:
    external: true
